defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "All4One-cifar10-blend" 
method: "all4one"
backbone:
  name: "resnet18"
method_kwargs:
  temperature: 0.2
  proj_hidden_dim: 2048
  pred_hidden_dim: 4096
  proj_output_dim: 256
  queue_size: 98304
momentum:
  base_tau: 0.99
  final_tau: 1.0
data:
  dataset: cifar10
  train_path: "../data/"
  val_path: "../data/"
  format: "image_folder" 
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 256
  lr: 1.0
  classifier_lr: 0.1
  weight_decay: 1e-5
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "../solo_models/"
  frequency: 1
auto_resume:
  enabled: False

# Backdoor attack configuration
backdoor:
  enabled: true
  name: "blend"
  target_label: 0
  poisoning_rate: 0.1
  cifar10_trigger_path: "../resources/hello_kitty.png"
  cifar100_trigger_path: "../resources/hello_kitty.png"
  imagenet_trigger_path: "../resources/imagenet_blend_trigger.png"
  blend_ratio: 0.1


# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed 