# All4One on CIFAR with BadNets backdoor poisoning

defaults:
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

name: "All4One-cifar10-badnets"
method: "all4one"

backbone:
  name: "resnet18"

method_kwargs:
  temperature: 0.2
  proj_hidden_dim: 2048
  pred_hidden_dim: 4096
  proj_output_dim: 256
  queue_size: 98304

momentum:
  base_tau: 0.99
  final_tau: 1.0

# Dataset
data:
  dataset: cifar10
  train_path: "./datasets/"
  val_path: null
  format: "image_folder"
  num_workers: 4
  fraction: -1.0

# Backdoor attack configuration
backdoor:
  enabled: true
  name: "badnets"
  target_label: 0
  poisoning_rate: 0.1
  cifar10_trigger_path: "./resources/cifar_1.png"
  cifar100_trigger_path: "./resources/cifar_1.png"

# Augmentations
augmentations:
  - crop_size: 32
    num_crops: 2
    rrc:
      enabled: true
      crop_min_scale: 0.2
      crop_max_scale: 1.0
    color_jitter:
      prob: 0.8
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
    grayscale:
      prob: 0.2
    gaussian_blur:
      prob: 0.0
    solarization:
      prob: 0.0
    equalization:
      prob: 0.0
    horizontal_flip:
      prob: 0.5

optimizer:
  name: "lars"
  batch_size: 256
  lr: 1.0
  classifier_lr: 0.1
  weight_decay: 1e-5
  kwargs:
    clip_lr: true
    eta: 0.02
    exclude_bias_n_norm: true

scheduler:
  name: "warmup_cosine"

checkpoint:
  enabled: true
  dir: "trained_models"
  frequency: 1

auto_resume:
  enabled: false

max_epochs: 800
devices: [0]
sync_batchnorm: true
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
